steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "📦 Subiendo build web a Google Cloud Storage"
        gsutil -m cp -r ./* gs://godot-builds/hello_test/

options:
  logging: CLOUD_LOGGING_ONLY
